const NOTES = {
  morning: [
    "Good morning. Today is here, fresh and unhurried. You can meet it one small moment at a time.",
    "You don’t need to have everything figured out this morning. One gentle beginning is enough.",
    "Let the morning arrive before you ask too much of yourself. There is time.",
    "May something small feel fresh today—the light through a window, cool water, or a breath of open air.",
    "However yesterday went, this morning is new. You are welcome to begin softly.",
    "Start with what feels kind and possible. The rest of the day can unfold from there.",
    "There is no need to rush into the day. Take a breath and let yourself arrive.",
    "A quiet start still counts as a start. Move gently and trust your own pace.",
    "Keep a little room for something bright today. It doesn’t have to be earned first.",
    "This morning is not asking you to be perfect. It is simply inviting you to begin.",
    "Choose the voice inside you that sounds like someone who loves you.",
    "May today ask less of you than you fear and offer more kindness than you expect.",
    "Before the world asks anything of you, remember this: your life is precious even on the days you feel ordinary.",
    "Your younger self would be so relieved to know you made it here. Be gentle with the person they grew into.",
    "Take some of the love you give so freely to everyone else and leave a little beside your own heart this morning.",
    "The kindness you have given has travelled farther than you will ever get to see. The world is softer because you tried.",
    "You do not have to become someone new today. The person waking up inside this morning is already worth caring for.",
    "If nobody has reminded you yet: I am glad you are here. This day would not be quite the same without you in it.",
    "Wake slowly. Your worth was already waiting for you before you opened your eyes.",
    "May you carry less pressure and more wonder into this morning. Not everything beautiful has to be productive.",
    "There is something brave about beginning again, even when all you did was get out of bed.",
    "You have survived every morning that once felt impossible. Let this one meet you with a little more mercy.",
    "Today does not need your best performance. It needs your honest presence, one moment at a time.",
    "Give yourself the kind of morning you would want for someone you deeply love.",
    "You are allowed to wake up hopeful without having a reason prepared.",
    "There is still softness in you after everything. That is not weakness; it is a quiet kind of miracle.",
    "Let your first thought be kind: you are here, you are trying, and that is a beautiful place to begin.",
    "May today bring one moment that reminds you why you kept going.",
    "The sun did not ask whether you were ready before it rose. You can begin without feeling ready, too.",
    "You deserve a life that feels gentle on the inside, not only one that looks successful from far away.",
    "This morning, choose one thing that makes your heart feel safe and let that be enough for now.",
    "Your pace is not a problem to solve. Move through this morning in the way your heart can manage.",
    "There are versions of you from years ago who would look at you now with such relief.",
    "You are more than the things you need to do today. You are a whole life unfolding.",
    "Let today surprise you. Some of your sweetest moments have not happened yet.",
    "Even if all you can offer this morning is a small, tired hope, it is still hope—and it still counts.",
    "May you feel at home in your own company today, even for just one quiet minute.",
    "Nothing about yesterday can make you undeserving of a soft beginning today.",
    "Breathe in as though the day has made room especially for you. In its own quiet way, it has.",
    "You woke up carrying a heart that has loved, hurt, healed, and kept beating. Treat it tenderly today."
  ],
  afternoon: [
    "You’ve already carried enough for one part of the day. Take this moment to soften your shoulders.",
    "The day is still yours. You can slow down, begin again, or choose one small next thing.",
    "You are allowed to pause in the middle of things. Rest does not need to wait until everything is done.",
    "If the day feels scattered, make it smaller: this hour, this breath, this one gentle choice.",
    "Whatever the morning held, there is still room for something lighter this afternoon.",
    "You don’t need to catch up with anyone. Continue at the pace your life needs.",
    "Perhaps this is a good moment for water, fresh air, and a little kindness toward yourself.",
    "A slow afternoon is not a wasted one. Quiet progress is still progress.",
    "You can leave some things unfinished. Your wellbeing belongs on the list, too.",
    "There is tenderness in trying again. You can meet yourself there right now.",
    "Take your time. You are doing more than you tend to give yourself credit for.",
    "Let the rest of today be imperfect and still worthwhile. Most good days are both.",
    "This version of you—the one who is tired and still trying—deserves tenderness, not another impossible standard.",
    "You are not a burden for needing care. You are a person, and people were never meant to carry everything alone.",
    "Some small kindness you once gave may still be living in someone’s memory. Goodness has a longer life than we know.",
    "If today has felt heavy, come back to yourself for a moment. You are still here, and that matters more than you think.",
    "You are allowed to be proud of surviving things you never speak about. Quiet courage is courage all the same.",
    "There is a place in this world shaped exactly like your presence. You do not need to earn the right to take it up.",
    "Pause for a second. You have already made it through every minute that brought you here.",
    "You can change the shape of this day without fixing all of it. One kind choice is enough to begin.",
    "Do not confuse being tired with being incapable. You may simply need care, not criticism.",
    "Your best can look quiet, slow, and uncertain. It is still your best, and it still deserves respect.",
    "You have permission to step away from what is draining you, even before you have explained yourself perfectly.",
    "Some days are for blooming. Some are for keeping your roots safe. Both are part of growing.",
    "The fact that you are still capable of kindness after difficult things says something beautiful about you.",
    "You do not have to make the whole day good. Find one honest moment and be present for it.",
    "May the next part of your day feel less like something to survive and more like somewhere you are allowed to be.",
    "Your nervous system deserves the same compassion you give your ambitions.",
    "If you need to begin again at two in the afternoon, begin again at two in the afternoon.",
    "There is no shame in needing reassurance. Even strong hearts like to know they are not alone.",
    "What if you spoke to yourself as though you were someone worth protecting? Because you are.",
    "A single peaceful minute can belong entirely to you, no matter how busy the day has become.",
    "You are not falling behind your own life. You are living it at the only pace available to you.",
    "Maybe you cannot see your progress because you have been standing too close to your own courage.",
    "Eat something, drink some water, unclench your jaw. Your body has been trying its best for you all day.",
    "The world will keep asking. You are allowed to answer yourself first for a little while.",
    "There is still time today for laughter, relief, an unexpected kindness, or a quiet change of heart.",
    "You can be grateful for your life and still need a break from carrying it.",
    "No one else can replace the particular warmth you bring into a room simply by being yourself.",
    "You have not missed your chance to make this day gentler. This moment is still yours."
  ],
  evening: [
    "You made it through today in all the ways that mattered. Let yourself soften now.",
    "The evening does not need anything from you right away. Take a quiet breath and arrive.",
    "Whatever remains unfinished can wait. You are allowed to put the day down gently.",
    "Be proud of the ways you kept going today that nobody else could see.",
    "A difficult part of the day does not get to define all of it. There was softness here, too.",
    "You can stop measuring the day now. Simply being here is enough for this moment.",
    "Let the light grow softer around you. You have carried enough for today.",
    "There is no prize for ending the day exhausted. Keep a little care for yourself.",
    "May this evening return a little of the energy you gave away today.",
    "You don’t have to solve tomorrow tonight. Let it stay where it belongs.",
    "Notice one small thing that felt good today, and let it be enough to hold for now.",
    "The day can be imperfect and still deserve a gentle ending.",
    "If you could see yourself through the eyes of someone who loves you, you might finally understand how much of you is worth holding dear.",
    "The people who love you do not love you for how much you finished today. You were never a list of completed things.",
    "Your younger self would be proud that you kept becoming, even through the days that asked too much of you.",
    "You may never know how many ordinary moments became warmer simply because you were there.",
    "Let tonight hold the part of you that stayed strong for everyone else. That part deserves somewhere soft to rest.",
    "You did not have to be extraordinary today to be deeply valuable. Being here was already enough.",
    "Come back to yourself now. The day has had enough of you; this evening can belong to you again.",
    "Not every victory looked impressive today. Some of them were simply the moments you chose not to give up.",
    "You are allowed to remember today by its softest moment instead of its hardest one.",
    "May your home, your room, or this small corner feel like somewhere your heart can finally exhale.",
    "You carried things today that nobody noticed. I hope you give yourself credit for their weight.",
    "There is nothing lazy about needing to recover from a day that asked a lot of you.",
    "Take off the version of yourself you wore for everyone else. You can just be you now.",
    "The unfinished things are not disappointed in you. They will still be there when you have more to give.",
    "You made thousands of tiny choices today, and many of them were kinder and braver than you realize.",
    "May something ordinary comfort you tonight: a familiar song, a warm drink, a light left on for you.",
    "If your heart feels tender, let it. Tenderness means you have not stopped caring.",
    "The day may not have gone the way you hoped, but you are still allowed a peaceful ending.",
    "You do not need to explain why you are tired before you deserve to rest.",
    "Let yourself be proud of the person who kept finding a way through today.",
    "Even on days when you feel invisible, your life leaves fingerprints of warmth on other people.",
    "You can forgive yourself for not being everything to everyone. You were never supposed to be.",
    "Somewhere between waking and now, you did enough. You can stop searching for proof.",
    "If today bruised your hope, hold it gently tonight. Hope can be quiet and still be alive.",
    "Your softness survived another day in a hard world. That is something worth honouring.",
    "You belong to yourself before you belong to any task, role, or expectation.",
    "May the evening remind you that slowing down is not the same as losing your way.",
    "There will be another sunrise. You do not have to carry tomorrow across tonight."
  ],
  night: [
    "Nothing more needs to be proven tonight. You are allowed to rest exactly as you are.",
    "The day is quiet now. Put down what you can and let tomorrow hold the rest.",
    "One tired moment cannot measure your whole life. Be gentle with yourself tonight.",
    "You have done enough for this day. Let your thoughts loosen their grip for a while.",
    "Rest is not something you need to earn. It is one of the ways you care for yourself.",
    "If your mind is busy, return to one breath. Nothing else needs your attention right now.",
    "May the night feel like a soft place to land, not another thing to get right.",
    "You can begin again tomorrow. For now, let the day be complete.",
    "There is nothing wrong with needing quiet, comfort, or a little more time.",
    "Let yourself be held by the stillness of this hour. You do not have to carry everything into sleep.",
    "Whatever today was, you are still worthy of tenderness tonight.",
    "The world can wait until morning. Take this time back for yourself.",
    "You are not hard to love. You are a whole person with tender places, and you deserve patience in every one of them.",
    "Sleep knowing the world did not need a perfect version of you today. It only needed the real one who kept showing up.",
    "Your heart has carried you through every day you thought might break it. Thank it by letting it be quiet now.",
    "If today made you feel small, remember that your worth did not shrink with the moment. It is still here, untouched.",
    "May you rest as if someone who loves you has tucked a blanket around your shoulders and whispered, ‘You have done enough.’",
    "Tomorrow can wait. Tonight, you are simply someone worth keeping safe, warm, and close to kindness.",
    "Let the pillow hold what your mind has been carrying. You do not need to keep watch over everything tonight.",
    "You are allowed to disappear into rest without first making the whole world okay.",
    "May sleep find the places in you that words could not soothe and bring them a little peace.",
    "Nothing you regret can be repaired by punishing yourself through the night. Rest, and meet it more gently tomorrow.",
    "You have spent enough hours being strong. Let the darkness ask nothing more of you.",
    "The person you are becoming needs tonight’s rest more than tonight’s overthinking.",
    "Even the moon moves through phases without apologizing for being less than full.",
    "You can close your eyes without knowing what comes next. Life will wait for you to wake.",
    "Whatever you could not finish today is not a verdict on who you are.",
    "May your dreams take you somewhere the weight cannot follow.",
    "Your body has been your home through every hard day. Offer it warmth, stillness, and thanks.",
    "You deserve the kind of rest that reaches deeper than sleep and reminds you that you are safe.",
    "It is okay if healing looked like doing almost nothing today. Quiet repair is still repair.",
    "The night is wide enough to hold every feeling you could not name.",
    "You do not need one more answer tonight. You need darkness, softness, and time.",
    "Somewhere inside you is a small, steady part that never stopped believing morning would come.",
    "May you wake tomorrow feeling a little less responsible for everything.",
    "There are people you have not met yet who will be grateful that your story kept going.",
    "Set down the conversations you keep replaying. You have already carried them far enough.",
    "You are still worthy of beautiful things, even after a day that did not feel beautiful.",
    "Tonight is not empty time. It is your life gently putting itself back together.",
    "Rest as though your only job now is to be held by the quiet."
  ]
};
